### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by MarcSolo** [scottaohara/a11y_styled_form_controls#36]
First, I want to say that this project is super helpful and will be sharing it with my peers. 

Here are the deets on the typo:

"A repository of styled and "styled" form control patterns, and **the they** are announced by screen readers."

Did you mean to write "and how they are announced by screen readers"?

HTH,
Marc

**Comment by scottaohara** [comment]
Thanks @MarcSolo :)

You're right, and [fixed](https://github.com/scottaohara/a11y_styled_form_controls/commit/6bd0f7acbd0618cbb7290d98ad76c66cdc507c4e).
