### ISSUE TITLE
Class missing in pattern markup for restyled radio

### ISSUE THREAD

**Issue by jfhector** [scottaohara/a11y_styled_form_controls#62]
#### Issue

In the Pattern Markup for the restyled radio on the [documentation page](https://scottaohara.github.io/a11y_styled_form_controls/src/radio-button/), the `input` element doesn't have a class name:

```html
<label class="n-radio-label">
  <input type="radio" name="n_radio" id="native_r2">
  <span>Label</span>
</label>
```

However, in the source HTML, the `input` element does have a `.n-radio` class, which is used in the CSS file:

```html
<label class="n-radio-label">
  <input type="radio" id="native_r2" name="n_radio" class="n-radio">
  <span>Restyle Option 1</span>
</label>
```

It looks like `class="n-radio"` is missing from the markup pattern documentation.

#### Thanks

This repo and your documentation are really helpful. Thanks for having done this work and sharing it like this.

**Comment by scottaohara** [comment]
Thanks for catching that!

I'll get this updated sometime soon, unless someone wants to get an easy PR accepted :)
